In [0]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from keras import optimizers

In [0]:
model=Sequential()

In [0]:
model.add(Dense(2,activation="sigmoid",input_dim=3))
model.add(Dense(3,activation="sigmoid"))
model.add(Dense(2))

In [0]:
model.layers[0].get_weights()

W0827 06:16:12.411241 140500848048000 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.



[array([[ 0.04714382,  0.46253264],
        [ 0.8720169 ,  0.68789184],
        [-0.30487287,  0.87167144]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [0]:
w12=np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
b1=np.array([0.4,0.2])
weights1=[w12,b1]
weights1

model.layers[0].set_weights(weights1)

In [0]:
model.layers[1].get_weights()

[array([[-1.046594  , -1.0375634 , -1.0319811 ],
        [-0.02674246,  0.27449644,  0.00653899]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [0]:
w23=np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
b2=np.array([0.1,0.1,0.2])
weights2=[w23,b2]
weights2

model.layers[1].set_weights(weights2)

In [0]:
model.layers[2].get_weights()

[array([[-0.46190536,  0.66487503],
        [-0.65922916,  0.03750181],
        [ 0.9437134 ,  0.7035314 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [0]:
w34=np.array([[0.3,0.2],[-0.5,0.5],[-0.7,0.2]])
b4=np.array([0.1,0.2])
weights3=[w34,b4]
weights3

model.layers[2].set_weights(weights3)

In [0]:

sgd = optimizers.SGD(lr=0.9)
model.compile(loss='mean_squared_error', optimizer=sgd,metrics=['accuracy'])

In [0]:
x=np.array([[1,0,1]])
y=np.array([[1,0]])
model.fit(x,y,epochs=1)


Epoch 1/1
1/1 [==============================] - 1s 508ms/step - loss: 0.7150 - acc: 1.0000


In [0]:
for i in range(3):
  print(model.layers[i].get_weights())
  print("\n\n\n\n\n")

[array([[ 0.2, -0.3],
       [ 0.4,  0.1],
       [-0.5,  0.2]], dtype=float32), array([0.4, 0.2], dtype=float32)]






[array([[-0.3       ,  0.19999999,  0.6       ],
       [-0.2       , -0.10000002, -0.20000002]], dtype=float32), array([0.1       , 0.09999998, 0.19999999], dtype=float32)]






[array([[ 0.30000004,  0.19999996],
       [-0.49999997,  0.49999994],
       [-0.6999999 ,  0.19999993]], dtype=float32), array([0.10000008, 0.19999988], dtype=float32)]








In [0]:
wup1=[x1 - x2 for (x1, x2) in zip(weights1, model.layers[0].get_weights())]
wup1


[array([[-2.98023223e-09,  1.19209290e-08],
        [-5.96046446e-09, -1.49011611e-09],
        [ 0.00000000e+00, -2.98023223e-09]]),
 array([-5.96046446e-09, -2.98023223e-09])]

In [0]:
wup2=[x1 - x2 for (x1, x2) in zip(weights2, model.layers[1].get_weights())]
wup2

[array([[ 1.19209290e-08,  1.19209290e-08, -2.38418579e-08],
        [ 2.98023223e-09,  1.63912773e-08,  1.78813934e-08]]),
 array([-1.49011611e-09,  2.08616257e-08,  1.19209290e-08])]

In [0]:
wup3=[x1 - x2 for (x1, x2) in zip(weights3, model.layers[2].get_weights())]
wup3

[array([[-4.17232514e-08,  4.17232514e-08],
        [-2.98023224e-08,  5.96046448e-08],
        [-7.15255737e-08,  7.15255737e-08]]),
 array([-7.59959221e-08,  1.16229057e-07])]